#ifndef ___ObjFileEditPanelHelper_H__
#define ___ObjFileEditPanelHelper_H__

// IDs for commons
enum IDsForObjEditor
{
	ID_TXT_FILE_NAME = 1000,
	ID_CMB_ATTRBUTES_NAME ,
	ID_CMB_ATTRBUTES_HINTS,
	ID_CMB_ENTITYS_NAME,
	ID_CMB_ENTITYS_FILE,
	ID_CMB_ENTITYS_MATERIAL,
	ID_CMB_MATERIALS_NAME,
	ID_CMB_MATERIALS_ENTITY,
	ID_CMB_MATERIALS_MATERIAL,
	ID_CMB_SLOTS_LOCATOR,
	ID_CMB_SLOTS_BONE,
	ID_CMB_SLOTS_SLOT,
	ID_CMB_SLOTS_OBJECT,
	ID_CMB_SLOTS_EFFECT,
	ID_CMB_EFFECTS_EFFECT,
	ID_CMB_EFFECTS_FILE,
	ID_CMB_EFFECTS_LOCATOR,

	ID_TXT_ATTRIBUTES_VALUE,
	ID_TXT_SLOTS_POS,
	ID_TXT_SLOTS_ROT,
	ID_TXT_EFFECTS_COLOUR,

	ID_CMB_SKELETONS_SKELETON,	
	ID_CMB_SKELETONS_RESOURCE,
	
	ID_BTN_SKELETONS_ADD,
	ID_BTN_SKELETONS_DEL,

	ID_BTN_RESET_POS,
	ID_BTN_RESET_ROT,

	ID_CHK_EFFECTS_TRANS,
	ID_CHK_SAVE_DEFAULT_SKELETON,
};

enum IndexForSwitchUI
{
	IFS_ALL = 0,
	IFS_FILE_SIZER,
	IFS_ATTRIBUTE_SIZER,
	IFS_ENTITY_SIZER,
	IFS_MATERIAL_SIZER,
	IFS_SLOTS_SIZER,	
	IFS_EFFECTS_SIZER,
	IFS_SKELETON_SIZER,
};

#endif
