//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: HeightMapScopeSetting.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_HeightMapScopeSetting_H__
#define __WDR_HeightMapScopeSetting_H__

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
    #pragma interface "HeightMapScopeSetting_wdr.h"
#endif

// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_MINHEIGHTTEXTCTRL = 10000;
const int ID_MAXHEIGHTTEXTCTRL = 10001;

wxSizer *HeightMapScopeSetting( wxWindow *parent, bool call_fit = TRUE, bool set_sizer = TRUE, wxString minHeight = wxT("0"), wxString maxHeight = wxT("0"));

// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
