
"AddCountryActionPoint",LuaAddActionPoint
"AddGuildUserPoint",LuaAddGuildUserPoint
"AddHonor",LuaAddHonor
"AddTotalGP",LuaAddTotalGP
"CountryDeletaBegin",LuaCountryDeletaBegin
"CountryVoteBegin",LuaCountryVoteBegin
"AddDyTitle",LuaFnAddDyTitle
"AddExp",LuaFnAddExp
"AddGlobalCountNews",LuaFnAddGlobalCountNews
"AddGPOwner",LuaFnAddGPOwner
"AddItem",LuaFnAddItem
"AddItemBonus",LuaFnAddItemBonus
"AddItemDemand",LuaFnAddItemDemand
"AddItemListToHuman",LuaFnAddItemListToHuman
"AddItemToBox",LuaFnAddItemToBox
"AddMission",LuaFnAddMission
"AddMissionEx",LuaFnAddMissionEx
"AddMoney",LuaFnAddMoney
"AddMoneyBonus",LuaFnAddMoneyBonus
"AddMonsterDropItem",LuaFnAddMonsterDropItem
"AddNumber",LuaFnAddNumber
"AddEventList""AddNumText",LuaFnAddNumText
"AddRadioItemBonus",LuaFnAddRadioItemBonus
"AddRandItemBonus",LuaFnAddRandItemBonus
"AddSkill",LuaFnAddSkill
"AddStorePointOnScene",LuaFnAddStorePointOnScene
"AddText",LuaFnAddText
"AddXinFa",LuaFnAddXinFa
"AwardBangpaiTitle",LuaFnAwardBangPaiTitle
"AwardJieBaiTitle",LuaFnAwardJieBaiTitle
"AwardNickTitle",LuaFnAwardNickTitle
"AwardShangDianTitle",LuaFnAwardShangDianTitle
"AwardShiTuTitle",LuaFnAwardShiTuTitle
"AwardSpouseTitle",LuaFnAwardSpouseTitle
"AwardTitle",LuaFnAwardTitle
"BankBegin",LuaFnBankBegin
"BeginAddItem",LuaFnBeginAddItem
"BeginEvent",LuaFnBeginEvent
"BeginUICommand",LuaFnBeginUICommand
"CalcPetDomesticationMoney",LuaFnCalcPetDomesticationMoney
"CallScriptFunction",LuaFnCallScriptFunction
"CancelPetPlacard",LuaFnCancelPetPlacard
"CheckSystemTimerValidity",LuaFnCheckSystemTimerValidity
"CheckTimer",LuaFnCheckTimer
"CityBuildingChange",LuaFnCityBuildingChange
"CityCreate",LuaFnCityCreate
"CityDelete",LuaFnCityDelete
"CityGetCityList",LuaFnCityGetCityList
"CityMoveTo",LuaFnCityMoveTo
"ClearFollowedMembers",LuaFnClearFollowedMembers
"CostMoney",LuaFnCostMoney
"CreateMonsterOnScene",LuaFnCreateMonsterOnScene
"DeleteTitle",LuaFnDeleteTitle
"DelGPOwner",LuaFnDelGPOwner
"DelItem",LuaFnDelItem
"DelMission",LuaFnDelMission
"DelSkill",LuaFnDelSkill
"DelStorePointOnScene",LuaFnDelStorePointOnScene
"DelXinFa",LuaFnDelXinFa
"DestroyMenPai",LuaFnDestroyMenPai
"DispatchAbilityInfo",LuaFnDispatchAbilityInfo
"DispatchAllTitle",LuaFnDispatchAllTitle
"DispatchEventList",LuaFnDispatchEventList
"DispatchMenpaiInfo",LuaFnDispatchMenpaiInfo
"DispatchMissionContinueInfo",LuaFnDispatchMissionContinueInfo
"DispatchMissionDemandInfo",LuaFnDispatchMissionDemandInfo
"DispatchMissionInfo",LuaFnDispatchMissionInfo
"DispatchMissionResult",LuaFnDispatchMissionResult
"DispatchMissionTips",LuaFnDispatchMissionTips
"DispatchPetPlacardList",LuaFnDispatchPetPlacardList
"DispatchRegieEventList",LuaFnDispatchRegieEventList
"DispatchShopItem",LuaFnDispatchShopItem
"DispatchUICommand",LuaFnDispatchUICommand
"DispatchXinfaLevelInfo",LuaFnDispatchXinfaLevelInfo
"EnableBankRentIndex",LuaFnEnableBankRentIndex
"EnableItemBoxPickOwnerTime",LuaFnEnableItemBoxPickOwnerTime
"EndAddItem",LuaFnEndAddItem
"EndEvent",LuaFnEndEvent
"EndUICommand",LuaFnEndUICommand
"EraseItem",LuaFnEraseItem
"ExpandBankSize",LuaFnExpandBankSize
"FindStorePointOnScene",LuaFnFindStorePointOnScene
"GeEquipReqLevel",LuaFnGeEquipReqLevel
"GetAbilityExp",LuaFnGetAbilityExp
"GetAbilityExpPlus",LuaFnGetAbilityExpPlus
"GetAbilityObjIndex",LuaFnGetAbilityObjIndex
"GetAbilityOperaRobotTime",LuaFnGetAbilityOperaRobotTime
"GetBagItemDur",LuaFnGetBagItemDur
"GetBagItemIdent",LuaFnGetBagItemIdent
"GetBagItemParam",LuaFnGetBagItemParam
"GetBankRentIndex",LuaFnGetBankRentIndex
"GetBankSize",LuaFnGetBankSize
"LuaFnGetBusPassengerIDIsInBus",LuaFnGetBusPassengerID_IsInBus
"GetCon",LuaFnGetCon
"GetCurCamp",LuaFnGetCurCamp
"GetCurCountry",LuaFnGetCurCountry
"GetDist",LuaFnGetDist
"GetDyTitlesNum",LuaFnGetDyTitlesNum
"GetExp",LuaFnGetExp
"GetFollowedMember",LuaFnGetFollowedMember
"GetFollowedMembersCount",LuaFnGetFollowedMembersCount
"GetGameTime",LuaFnGetGameTime
"GetGemEmbededCount",LuaFnGetGemEmbededCount
"GetGPCountByOwner",LuaFnGetGPCountByOwner
"GetHp",LuaFnGetHp
"GetHumanEnergy",LuaFnGetHumanEnergy
"GetHumanEnergyRegeneRate",LuaFnGetHumanEnergyRegeneRate
"GetHumanGUID",LuaFnGetHumanGUID
"GetHumanHairColor",LuaFnGetHumanHairColor
"GetHumanHairModel",LuaFnGetHumanHairModel
"GetHumanMaxEnergy",LuaFnGetHumanMaxEnergy
"GetHumanMaxVigor",LuaFnGetHumanMaxVigor
"GetHumanVigor",LuaFnGetHumanVigor
"GetHumanVigorRegeneRate",LuaFnGetHumanVigorRegeneRate
"GetHumanWorldX",LuaFnGetHumanWorldX
"GetHumanWorldZ",LuaFnGetHumanWorldZ
"GetItemBoxMaxGrowTime",LuaFnGetItemBoxMaxGrowTime
"GetItemBoxOpenFlag",LuaFnGetItemBoxOpenFlag
"GetItemBoxOwner",LuaFnGetItemBoxOwner
"GetItemBoxRecycleTimes",LuaFnGetItemBoxRecycleTimes
"GetItemBoxRequireAbilityID",LuaFnGetItemBoxRequireAbilityID
"GetItemBoxWorldPosX",LuaFnGetItemBoxWorldPosX
"GetItemBoxWorldPosZ",LuaFnGetItemBoxWorldPosZ
"GetItemCount",LuaFnGetItemCount
"GetItemEquipPoint",LuaFnGetItemEquipPoint
"GetItemIndex",LuaFnGetItemIndex
"GetItemIsEmpty",LuaFnGetItemIsEmpty
"GetItemQuality",LuaFnGetItemQuality
"GetItemTableIndexByIndex",LuaFnGetItemTableIndexByIndex
"GetLevel",LuaFnGetLevel
"GetMenPai",LuaFnGetMenPai
"GetMenPaiFigure",LuaFnGetMenPaiFigure
"GetMenPaiMaster",LuaFnGetMenPaiMaster
"GetMenPaiTitle",LuaFnGetMenPaiTitle
"GetMission",LuaFnGetMission
"GetMissionCount",LuaFnGetMissionCount
"GetMissionData",LuaFnGetMissionData
"GetMissionDataBit",LuaFnGetMissionDataBit
"GetMissionIndexByID",LuaFnGetMissionIndexByID
"GetMissionParam",LuaFnGetMissionParam
"GetMoney",LuaFnGetMoney
"GetMonsterCount",LuaFnGetMonsterCount
"GetMonsterDataID",LuaFnGetMonsterDataID
"GetMonsterGroupID",LuaFnGetMonsterGroupID
"GetMonsterObjID",LuaFnGetMonsterObjID
"GetMonsterOwnerCount",LuaFnGetMonsterOwnerCount
"GetMonsterOwnerID",LuaFnGetMonsterOwnerID
"GetMonsterTeamID",LuaFnGetMonsterTeamID
"GetMp",LuaFnGetMp
"GetName",LuaFnGetName
"GetNearTeamCount",LuaFnGetNearTeamCount
"GetNearTeamMember",LuaFnGetNearTeamMember
"GetNumText""GetEventList",LuaFnGetNumText
"LuaFnGetPet_IntPerception",LuaFnGetPet_ConstitutionPerception
"LuaFnGetPet_DexPerception",LuaFnGetPet_MindPerception
"LuaFnGetPet_ConPerception",LuaFnGetPet_SmartnessPerception
"GetQuestionsRecord",LuaFnGetQuestionsRecord
"GetSceneNPCPos",LuaFnGetSceneNPCPos
"GetSex",LuaFnGetSex
"GetStoreMapSceneID",LuaFnGetStoreMapSceneID
"GetStoreMapX",LuaFnGetStoreMapX
"GetStoreMapZ",LuaFnGetStoreMapZ
"GetStorePointType",LuaFnGetStorePointType
"GetSystemTimerParam",LuaFnGetSystemTimerParam
"GetTeamId",LuaFnGetTeamId
"GetTeamMemberGuid",LuaFnGetTeamMemberGuid
"GetTeamSceneMemberCount",LuaFnGetTeamSceneMemberCount
"GetTeamSize",LuaFnGetTeamSize
"GetTitle",LuaFnGetTitle
"GetTodayDate",LuaFnGetTodayDate
"GetWorldPos",LuaFnGetWorldPos
"GuildCreate",LuaFnGuildCreate
"GuildList",LuaFnGuildList
"HaveItem",LuaFnHaveItem
"HaveItemInBag",LuaFnHaveItemInBag
"HaveSkill",LuaFnHaveSkill
"HaveXinFa",LuaFnHaveXinFa
"IsCanEnterCopyScene",LuaFnIsCanEnterCopyScene
"IsCaptain",LuaFnIsCaptain
"IsEquipItem",LuaFnIsEquipItem
"IsHaveMission",LuaFnIsHaveMission
"IsInDist",LuaFnIsInDist
"IsMissionHaveDone",LuaFnIsMissionHaveDone
"IsMissionInTime",LuaFnIsMissionInTime
"IsPrescrLearned",LuaFnIsPrescrLearned
"IssuePetPlacard",LuaFnIssuePetPlacard
"IssuePetPlacardByIndex",LuaFnIssuePetPlacardByIndex
"IsTeamFollow",LuaFnIsTeamFollow
"IsTodayMission",LuaFnIsTodayMission
"ItemBoxEnterScene",LuaFnItemBoxEnterScene
"LeaveTeam",LuaFnLeaveTeam
"MissionCom",LuaFnMissionCom
"MissionCommonCheck",LuaFnMissionCommonCheck
"Msg2Player",LuaFnMsg2Player
"Msg2Team",LuaFnMsg2Team
"NewWorld",LuaFnNewWorld
"NpcMsg2Player",LuaFnNpcMsg2Player
"PetDomestication",LuaFnPetDomestication
"PetStudySkill",LuaFnPetStudySkill
"PetStudySkill_MenPai",LuaFnPetStudySkill_MenPai
"PrintNum",LuaFnPrintNum
"PrintStr",LuaFnPrintStr
"OpenRndomBox",LuaFnProcessOpenBox
"QueryAreaStandingTime",LuaFnQueryAreaStandingTime
"QueryHumanAbility",LuaFnQueryHumanAbility
"QueryHumanAbilityLevel",LuaFnQueryHumanAbilityLevel
"RemoveMonster",LuaFnRemoveMonster
"ResetAreaStandingTime",LuaFnResetAreaStandingTime
"RestoreHp",LuaFnRestoreHp
"RestoreMp",LuaFnRestoreMp
"RestoreNpcCamp",LuaFnRestoreNpcCamp
"SetAbilityExp",LuaFnSetAbilityExp
"SetAbilityOperaRobotTime",LuaFnSetAbilityOperaRobotTime
"SetAbilityOperaTime",LuaFnSetAbilityOperaTime
"SetBagItemDur",LuaFnSetBagItemDur
"SetBagItemIdent",LuaFnSetBagItemIdent
"SetBagItemParam",LuaFnSetBagItemParam
"SetCurCamp",LuaFnSetCurCamp
"SetHumanAbilityLevel",LuaFnSetHumanAbilityLevel
"SetHumanEnergy",LuaFnSetHumanEnergy
"SetHumanEnergyRegeneRate",LuaFnSetHumanEnergyRegeneRate
"SetHumanHairColor",LuaFnSetHumanHairColor
"SetHumanHairModel",LuaFnSetHumanHairModel
"SetHumanMaxEnergy",LuaFnSetHumanMaxEnergy
"SetHumanMaxVigor",LuaFnSetHumanMaxVigor
"SetHumanVigor",LuaFnSetHumanVigor
"SetHumanVigorRegeneRate",LuaFnSetHumanVigorRegeneRate
"SetItemBoxMaxGrowTime",LuaFnSetItemBoxMaxGrowTime
"SetItemBoxOwner",LuaFnSetItemBoxOwner
"SetItemBoxPickOwnerTime",LuaFnSetItemBoxPickOwnerTime
"SetItemBoxRecycleTimes",LuaFnSetItemBoxRecycleTimes
"SetLevel",LuaFnSetLevel
"SetMenPai",LuaFnSetMenPai
"SetMissionByIndex",LuaFnSetMissionByIndex
"SetMissionData",LuaFnSetMissionData
"SetMissionDataBit",LuaFnSetMissionDataBit
"SetMissionEvent",LuaFnSetMissionEvent
"SetNpcCurCamp",LuaFnSetNpcCurCamp
"SetPatrolId",LuaFnSetPatrolId
"SetPos",LuaFnSetPos
"SetPrescription",LuaFnSetPrescription
"SetRevPos",LuaFnSetRevPos
"SetSystemTimerParam",LuaFnSetSystemTimerParam
"SetSystemTimerTick",LuaFnSetSystemTimerTick
"SetTeamFollowSpeed",LuaFnSetTeamFollowSpeed
"SetTimeParam",LuaFnSetTimeParam
"SetTimer",LuaFnSetTimer
"ShowNpcEventList",LuaFnShowNpcEventList
"StartupSystemTimer",LuaFnStartupSystemTimer
"StopSystemTimer",LuaFnStopSystemTimer
"StopTeamFollow",LuaFnStopTeamFollow
"StopTimer",LuaFnStopTimer
"TryRecieveItem",LuaFnTryRecieveItem
"UICommand_AddInt",LuaFnUICommand_AddInt
"UICommand_AddString",LuaFnUICommand_AddString
"UseItem",LuaFnUseItem
"UseSkill",LuaFnUseSkill
"GetDayTime",LuaGetDayTime
"GetObjCreateTime",LuaGetObjCreateTime
"SetPlayerDefaultReliveInfo",LuaSetPlayerDefaultReliveInfo
"SubCountryActionPoint",LuaSubActionPoint
"SubGuildUserPoint",LuaSubGuildUserPoint
"SubHonor",LuaSubHonor
"SubTotalGP",LuaSubTotalGP