//------------------------------------------------------------------------------
// Header generated by wxDesigner from file: ParticleEditor.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------

#ifndef __WDR_ParticleEditor_H__
#define __WDR_ParticleEditor_H__


// Include wxWidgets' headers

#ifndef WX_PRECOMP
    #include <wx/wx.h>
#endif

#include <wx/image.h>
#include <wx/statline.h>
#include <wx/spinbutt.h>
#include <wx/spinctrl.h>
#include <wx/splitter.h>
#include <wx/listctrl.h>
#include <wx/treectrl.h>
#include <wx/notebook.h>
#include <wx/grid.h>
#include <wx/toolbar.h>

// Declare window functions

const int ID_COMBO_PARTICLE_EMITTER = 10100;
const int ID_COMBO_PARTICLE_AFFECTOR = 10101;
// Declare menubar functions

// Declare toolbar functions

// Declare bitmap functions

#endif

// End of generated file
