//------------------------------------------------------------------------------
// Source code generated by wxDesigner from file: ParticleEditor.wdr
// Do not modify this file, all changes will be lost!
//------------------------------------------------------------------------------



// For compilers that support precompilation
#include "wx/wxprec.h"

#ifdef __BORLANDC__
    #pragma hdrstop
#endif

// Include private header
#include "EffectObjectEditor_wdr.h"

#include <wx/intl.h>


#include <wx/propgrid/propgrid.h>
#include <wx/propgrid/manager.h>


// Implement window functions

// Implement menubar functions

// Implement toolbar functions

// Implement bitmap functions


// End of generated file
